############################################
####  Postgres Database config          #### 
############################################

development:
 adapter: postgresql
 database: ykwx_development
 host: localhost
 pool: 5
 timeout: 5000

test:
 adapter: postgresql
 database: ykwx_test
 host: localhost
 pool: 5
 timeout: 5000

production:
 adapter: postgresql
 database: ykwx_production
 host: localhost
 pool: 5
 timeout: 5000
